# counties_config.py
# Complete list of all 72 Wisconsin counties with their county numbers

WISCONSIN_COUNTIES = [
    {"countyNo": 1, "countyName": "Adams County"},
    {"countyNo": 2, "countyName": "Ashland County"},
    {"countyNo": 3, "countyName": "Barron County"},
    {"countyNo": 4, "countyName": "Bayfield County"},
    {"countyNo": 5, "countyName": "Brown County"},
    {"countyNo": 6, "countyName": "Buffalo County"},
    {"countyNo": 7, "countyName": "Burnett County"},
    {"countyNo": 8, "countyName": "Calumet County"},
    {"countyNo": 9, "countyName": "Chippewa County"},
    {"countyNo": 10, "countyName": "Clark County"},
    {"countyNo": 11, "countyName": "Columbia County"},
    {"countyNo": 12, "countyName": "Crawford County"},
    {"countyNo": 13, "countyName": "Dane County"},
    {"countyNo": 14, "countyName": "Dodge County"},
    {"countyNo": 15, "countyName": "Door County"},
    {"countyNo": 16, "countyName": "Douglas County"},
    {"countyNo": 17, "countyName": "Dunn County"},
    {"countyNo": 18, "countyName": "Eau Claire County"},
    {"countyNo": 19, "countyName": "Florence County"},
    {"countyNo": 20, "countyName": "Fond du Lac County"},
    {"countyNo": 21, "countyName": "Forest County"},
    {"countyNo": 22, "countyName": "Grant County"},
    {"countyNo": 23, "countyName": "Green County"},
    {"countyNo": 24, "countyName": "Green Lake County"},
    {"countyNo": 25, "countyName": "Iowa County"},
    {"countyNo": 26, "countyName": "Iron County"},
    {"countyNo": 27, "countyName": "Jackson County"},
    {"countyNo": 28, "countyName": "Jefferson County"},
    {"countyNo": 29, "countyName": "Juneau County"},
    {"countyNo": 30, "countyName": "Kenosha County"},
    {"countyNo": 31, "countyName": "Kewaunee County"},
    {"countyNo": 32, "countyName": "La Crosse County"},
    {"countyNo": 33, "countyName": "Lafayette County"},
    {"countyNo": 34, "countyName": "Langlade County"},
    {"countyNo": 35, "countyName": "Lincoln County"},
    {"countyNo": 36, "countyName": "Manitowoc County"},
    {"countyNo": 37, "countyName": "Marathon County"},
    {"countyNo": 38, "countyName": "Marinette County"},
    {"countyNo": 39, "countyName": "Marquette County"},
    {"countyNo": 40, "countyName": "Menominee County"},
    {"countyNo": 41, "countyName": "Milwaukee County"},
    {"countyNo": 42, "countyName": "Monroe County"},
    {"countyNo": 43, "countyName": "Oconto County"},
    {"countyNo": 44, "countyName": "Oneida County"},
    {"countyNo": 45, "countyName": "Outagamie County"},
    {"countyNo": 46, "countyName": "Ozaukee County"},
    {"countyNo": 47, "countyName": "Pepin County"},
    {"countyNo": 48, "countyName": "Pierce County"},
    {"countyNo": 49, "countyName": "Polk County"},
    {"countyNo": 50, "countyName": "Portage County"},
    {"countyNo": 51, "countyName": "Price County"},
    {"countyNo": 52, "countyName": "Racine County"},
    {"countyNo": 53, "countyName": "Richland County"},
    {"countyNo": 54, "countyName": "Rock County"},
    {"countyNo": 55, "countyName": "Rusk County"},
    {"countyNo": 56, "countyName": "Sauk County"},
    {"countyNo": 57, "countyName": "Sawyer County"},
    {"countyNo": 58, "countyName": "Shawano County"},
    {"countyNo": 59, "countyName": "Sheboygan County"},
    {"countyNo": 60, "countyName": "St. Croix County"},
    {"countyNo": 61, "countyName": "Taylor County"},
    {"countyNo": 62, "countyName": "Trempealeau County"},
    {"countyNo": 63, "countyName": "Vernon County"},
    {"countyNo": 64, "countyName": "Vilas County"},
    {"countyNo": 65, "countyName": "Walworth County"},
    {"countyNo": 66, "countyName": "Washburn County"},
    {"countyNo": 67, "countyName": "Washington County"},
    {"countyNo": 68, "countyName": "Waukesha County"},
    {"countyNo": 69, "countyName": "Waupaca County"},
    {"countyNo": 70, "countyName": "Waushara County"},
    {"countyNo": 71, "countyName": "Winnebago County"},
    {"countyNo": 72, "countyName": "Wood County"},
]

# Alternative: Import this in your main script
if __name__ == "__main__":
    print(f"Total Wisconsin Counties: {len(WISCONSIN_COUNTIES)}")
    for county in WISCONSIN_COUNTIES:
        print(f"  {county['countyNo']:2d}. {county['countyName']}")